Controllers films users
LinarJC/java-filmorate pull request #3
Opened 2022-07-03 13:33 UTC by LinarJC

каркас springboot приложения filmorate по ТЗ спринта 8. 1-ая итерация проверки.

2022-07-03 18:20 UTC, eugene-lenkevich requested changes
Привет,  Линар, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-03 18:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new RuntimeException("Указанная дата релиза не может быть ранее 28 декабря 1895 года.");
А подходит ли для данной ситуации непроверяемое исключение?
Пользователь ввел некорректные данные - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
которое extends Exception

2022-07-03 18:20 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (user.getName().isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2022-07-06 15:39 UTC, LinarJC commented
Привет, Евгений, надеюсь всё понял правильно) Применил проверяемое исключение и воспользовался инструментом StringUtils

2022-07-06 18:48 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-07-06 18:48 UTC, eugene-lenkevich commented
> Привет, Евгений, надеюсь всё понял правильно) Применил проверяемое исключение и воспользовался инструментом StringUtils

Ага, все норм :)

2022-07-06 18:49 UTC, eugene-lenkevich approved these changes

2022-07-07 14:46 UTC, merged