refactor: внедрить функционал с лайками и друзьями.
LinarJC/java-filmorate pull request #4
Opened 2022-08-01 18:51 UTC by LinarJC

2022-08-02 05:07 UTC, EugeneLenkevich requested changes
Привет, Линар, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-08-02 05:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if(!filmStorage.getFilms().containsKey(film.getId())) {
А не лучше ли в сторедже создать соответствующий поисковый метод и всю логику поиска поместить в него? 
Так мы спрячем детали реализации. Допустим, потом у нас появится база данных, нам будет достаточно только переписать метод стореджа, а так продеться искать подобный код по всем сервисам :)

filmStorage.getFilms() -> filmStorage.isExist(film)

2022-08-02 05:07 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((o1, o2) -> o2.getUserIds().size() - o1.getUserIds().size()).collect(Collectors.toList());
findTopAllFilms - дословно "найти первые все фильмы", не совсем понятно что делает этот метод, предположду что Top тут лишнее, так как это сделает как раз соседний метод :)
Ну и лучше сортировку опять таки перенести на уровень стореджа

Вообще, обычно вот так логика располагается по слоям спрингового приложения:

"Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.

Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.

Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса."

2022-08-02 19:40 UTC, LinarJC commented
Привет, Евгений) Принял к вниманию все замечания и внес следующие изменения: 
- убрал лишний код и конструкторы, 
- перераспределил функционал между слоями приложения, 
- оптимизировал названия методов на более внятные

2022-08-03 03:10 UTC, EugeneLenkevich requested changes
Привет, все гут, но в сервисами получилась другая крайность: в сторедж перехала вся бизнес логика, не совсем то что нужно, в сторедж надо перенести только поисковые методы, саму верхнеуровевую логику, валидацию и пр. стоит в сервисах оставить :)

2022-08-03 03:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -        final Film film = filmStorage.findFilm(filmId);
Это уже бизнес логика, ее то не стоит переносить в сторедж :)

2022-08-03 03:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -        if(!filmStorage.getFilms().containsKey(film.getId())) {
Идея в том чтобы перенести в сторедж только методы выборки данных (плюс сохранения, обновления и удаления)
То есть
в сервисе точно стоит оставить
- валидацию
- логирование
- саму высокоуровневую логику обновления

то есть  примерно так

             if(filmStorage.ifNotExist(film)) { 
                   throw ...
              }

            filmStorage.updateFilm(film);
            log.info("Внесены изменения в фильм: '{}', ID '{}'", film.getName(), film.getId());
            return film;

2022-08-03 03:18 UTC, EugeneLenkevich requested changes
Оставил несколько комментариев для примера, в общем основной смысл в том чтобы в сторедж перенести выборки и сортировки и прочую обработку именно данных самих по себе

2022-08-03 03:18 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        validate(film);
Тут все кроме films.replace(...) - бизнес-логика, ее бы в сервис :)

2022-08-03 03:18 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void addLike(Film film, User user) {
Весь бы метод в сервис поднять, тут все не про хранение данных :)

2022-08-03 03:18 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        Collection<Film> sortedList = findAllFilms().stream()
А вот тут  все ок, выборка, сортировка и ораничение все в сторежде, так и должно быть, это и имелось в виду :)

2022-08-03 03:18 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        users.put(user.getId(), user);
Все выше в методе - бизнес-логика :)

2022-08-04 14:54 UTC, LinarJC commented
Привет, спасибо за комментарии с примерами выше)   смысл и логика построения уровней или слоев стала яснее. Перераспределил функционал уже в другом новом понимании

2022-08-04 17:12 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-08-04 17:14 UTC, EugeneLenkevich commented
> Привет, спасибо за комментарии с примерами выше) смысл и логика построения уровней или слоев стала яснее. Перераспределил функционал уже в другом новом понимании

Привет, супер, если в целом стало понятнее то отлично, это самое главное :)

2022-08-07 15:52 UTC, merged